### ISSUE TITLE
react 0.14 support ?

### ISSUE THREAD

**Issue by mydearxym** [stoeffel/react-cond#21]
amazing work !
my project  is using react 0.14  and `react-cond` 's Clause syntax  does not work ...
good news is  the regular way is work : 
```jsx
<Cond value={text}>
    {[ isTrue, <Greenspot key='1' /> ]}
    {[ isFalse, <Redspot key='1' /> ]}
    {[ otherwise, <span key='2'>?</span> ]}
 </Cond>
```
and i have to manually add key attr to each Component to avoid warnings , is this a bug ?

**Comment by stoeffel** [comment]
> amazing work !

Thanks a lot :smile: 

> my project is using react 0.14 and react-cond 's Clause syntax does not work ...

Hmm. it works for me and it works in the tests (See #23). Could you add a example where it doesn't work?

> and i have to manually add key attr to each Component to avoid warnings , is this a bug ?

It's not a bug. You have to add the [key attribute](https://facebook.github.io/react/docs/multiple-components.html#dynamic-children) to each child component.
Maybe we could improve the docs. Would you like to make a PR?

**Comment by stoeffel** [comment]
@mydearxym any news?

**Comment by mydearxym** [comment]
@stoeffel   sorry for my delay ...
[here](https://github.com/mydearxym/react_cond_test) is a simple example use react 0.14.x  which the Clause syntax cause a error .

and Clause syntax  seems to no need to add key attribute manually ?

**Comment by stoeffel** [comment]
Hi @mydearxym. Thx for your reply. I actually don't see how we could add the key attribute automatically. I think the only solution is to add a key to each child (and update the docs). Or do you have an idea how to add the `key` automatically?

**Comment by stoeffel** [comment]
The funny thing is that this:

``` jsx
  render() {
    return (
      <Cond value={this.state.test}>
        <Clause test={x => x > 0}>
          <Positive key='pos' />
        </Clause>
        <Clause test={x => x < 0}>
          <Negative key='neg' />
        </Clause>
        <Clause test={x => x == 0}>
          <Zero key='zer' />
        </Clause>
        <Default>
          <Zero key='zero'/>
        </Default>
      </Cond>
    )
  }
```

works.

But if `clause` and the child component is on the same line it fails.

``` jsx
      <Cond value={this.state.test}>
       <Clause test={x => x > 0}> <Positive key='pos' /> </Clause>
       <Clause test={x => x < 0}> <Negative key='neg' /> </Clause>
       <Clause test={x => x == 0}> <Zero key='zer' /> </Clause>
       <Default><Zero key='zero'/></Default>
      </Cond>
```

It looks like this is a babel issue. See [the transpiled code](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=true&code=%3Cdiv%3E%20%20%20%0A%20%20%20%20%20%20%3CCond%20value%3D%7Bthis.state.test%7D%3E%0A%20%20%20%20%20%20%20%3CClause%20test%3D%7Bx%20%3D%3E%20x%20%3E%200%7D%3E%20%3CPositive%20key%3D'pos'%20%2F%3E%20%3C%2FClause%3E%0A%20%20%20%20%20%20%20%3CClause%20test%3D%7Bx%20%3D%3E%20x%20%3C%200%7D%3E%20%3CNegative%20key%3D'neg'%20%2F%3E%20%3C%2FClause%3E%0A%20%20%20%20%20%20%20%3CClause%20test%3D%7Bx%20%3D%3E%20x%20%3D%3D%200%7D%3E%20%3CZero%20key%3D'zer'%20%2F%3E%20%3C%2FClause%3E%0A%20%20%20%20%20%20%20%3CDefault%3E%3CZero%20key%3D'zero'%2F%3E%3C%2FDefault%3E%0A%20%20%20%20%20%20%3C%2FCond%3E%0A%20%20%20%20%20%20%0A%20%20%20%3CCond%20value%3D%7Bthis.state.test%7D%3E%0A%20%20%20%20%20%20%20%20%3CClause%20test%3D%7Bx%20%3D%3E%20x%20%3E%200%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3CPositive%20key%3D'pos'%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FClause%3E%0A%20%20%20%20%20%20%20%20%3CClause%20test%3D%7Bx%20%3D%3E%20x%20%3C%200%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3CNegative%20key%3D'neg'%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FClause%3E%0A%20%20%20%20%20%20%20%20%3CClause%20test%3D%7Bx%20%3D%3E%20x%20%3D%3D%200%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3CZero%20key%3D'zer'%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FClause%3E%0A%20%20%20%20%20%20%20%20%3CDefault%3E%0A%20%20%20%20%20%20%20%20%20%20%3CZero%20key%3D'zero'%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FDefault%3E%0A%20%20%20%20%20%20%3C%2FCond%3E%0A%3C%2Fdiv%3E)

**Comment by stoeffel** [comment]
Same happens without react-cond:

This:

``` jsx
<div>   

  <div value={this.state.test}>
    <h1> <span>SPACES</span> </h1>
  </div>

  <div value={this.state.test}>
    <h1>
      <span>LINE BREAKS</span>
    </h1>
  </div>

</div>
```

transpiles to:

``` jsx
"use strict";

React.createElement(
  "div",
  null,
  React.createElement(
    "div",
    { value: undefined.state.test },
    React.createElement(
      "h1",
      null,
      " ",
      React.createElement(
        "span",
        null,
        "SPACES"
      ),
      " "
    )
  ),
  React.createElement(
    "div",
    { value: undefined.state.test },
    React.createElement(
      "h1",
      null,
      React.createElement(
        "span",
        null,
        "LINE BREAKS"
      )
    )
  )
);
```
